### ISSUE TITLE
Analyze X and Y sort issue

### ISSUE THREAD

**Issue by priscilla-glenn** [colomemaria/epiAneufinder#12]
Hi, 
Is it possible to analyze the X and Y chromosome as well? I ran epiAneufinder on mice and when I tried to include them, I get the following error:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions

My first thought was to rename the X and Y and chr20 and chr21 but I'm not sure how that will work with the reference genome input, genome="BSgenome.Mmusculus.UCSC.mm10".

Thoughts? 

Thanks! Priscilla

**Comment by thek71** [comment]
Hi Priscilla,

this error doesn't seem to come from the two additional chromosomes you used.
I would check whether the naming in the fragment file is consistent with the naming in the mm10 genome you are using.
Please tell me if this solves the issue.

Best,
Katia

**Comment by Urja25** [comment]
Hi Priscilla,
I am also trying to run the tool for mouse data but run into the following error message:
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions
Calls: epiAneufinder ... lapply -> lapply -> FUN -> rowSums -> rowSums ->
Execution halted

Do you know what this could be?
How did you end up solving your issue?

Thanks a lot!

Best,
Urja

**Comment by YiweiNiu** [comment]
Hi,

Similar error when using 10 Mb window size for human hg38 data. Here is the error message:

```r
Subtracting Blacklist...
Adding Nucleotide Information...
1 of 21
2 of 21
3 of 21
4 of 21
5 of 21
6 of 21
7 of 21
8 of 21
9 of 21
10 of 21
11 of 21
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions
Calls: <Anonymous> ... lapply -> lapply -> FUN -> rowSums -> rowSums -> <Anonymous>
In addition: Warning message:
In dir.create(outdir, recursive = TRUE) :
  'Ts18_F_4E.d500.10M/epiAneufinder_results' already exists
Execution halted
```

Using the default window size (10 kb) is fine.

Bests,
Yiwei

**Comment by KatharinaSchmid** [comment]
Hi everyone,
sorry for the delayed answer, but we probably found the reason. This error message occurs in cases where one chromosome is so small that it is separated only into one bin (either for very small chromosomes or very large bin sizes). We fixed this problem in our current update of the package (v1.0.2), so I close this issue for now. If you still have problems with the new version of epiAneufinder, please let us know and reopen the issue.
