### ISSUE TITLE
Problem while "Adding Nucleotide Information"

### ISSUE THREAD

**Issue by BoxWong** [colomemaria/epiAneufinder#20]
Hi Katia,
I ran into a problem when I changed window size from 1e6 to 1e7. The error was:

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions

**The full log is as follows:**
There were 31 warnings (use warnings() to see them)
Subtracting Blacklist...
Adding Nucleotide Information...
1 of 21
2 of 21
3 of 21
4 of 21
5 of 21
6 of 21
7 of 21
8 of 21
9 of 21
10 of 21
11 of 21
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions
Calls: epiAneufinder ... lapply -> lapply -> FUN -> rowSums -> rowSums -> <Anonymous>

I also noticed that it always stopped when adding Nueclotide Information for 11. And it was fine with bin size set to 1e6 or 5e6, any idea why that was the case? Any solution?

Thank you in advance :)
Xin

**Comment by thek71** [comment]
Hi Xin,

we have seen this error before and it happened when the chromosome is small for the bin size and only one bin is created. We provided a solution for this, in version 1.0.2. Can you please check which version of epiAneufinder you are running?
Please tell us if the error persists, so that we can a second look.

Best,
Katia

**Comment by BoxWong** [comment]
Hi Katia, 

thanks for the heads-up. I checked the version that I used for the initial run, and it was 0.1.0 (probably an early user, right?). I've updated it to 1.0.3 and now it seems to have resolved the issue. 
Thanks again for the great tool.

Best, 
Xin

**Comment by thek71** [comment]
Hi Xin,

glad that everything works!
I am closing the issue, since it's been resolved.

Best,
Katia
