### ISSUE TITLE
How are "normal" cells defined in EpiAneufinder ?

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [colomemaria/epiAneufinder#32]
Hello, Thanks for making this package. Have a few questions . 

The paper describes how different bins/segments are allocated as gain/loss/normal. In addition, the tool allocates a "sub-clone" for almost every cell in every sample. 

* Could you elaborate on how "normal" cells are defined in EpiAneufinder ? Is there a way to identify "normal" cells in a sample based on either the CNV output or sub-clone output ? 

* In the EpiAneufinder results per-sample, we see a bunch of cells that don't have allocated "sub-clones". Are these "normal" cells ? Or are they filtered out due to low bin coverage ? 

Thanks, K

**Comment by Krithika-Bhuvan** [comment]
Thank you so much for the response, its very helpful. We have RNA data as well, so we will work to define a gene list that can help us identify this. 

Some follow up questions related to Low coverage cells (this was my second question in the previous section) . 
(1) We seem to have quite a bit of low coverage cells that were filtered out before CNV analysis.  Can you give some insight on how Low coverage cells are identified and filtered out ? 
(2) Is there a way to adjust the threshold for the determination of "Low coverage cells" - are there any settings we change to play around with this ? Right now I used default setting and about half or more cells seem to have been filtered out. 

Thanks, K

**Comment by thek71** [comment]
Hi Krithika,

as is described in the paper, we consider low quality cells that have a number of fragments less than 20,000 by default.
But this is a parameter that can be chosen by the user as well.
You just need to change the minFrags=20000 parameter to the value that suits better your dataset.

Best,
Katia

**Comment by Krithika-Bhuvan** [comment]
Thank you very much Katia ! Super helpful . Lots to think about. 
I saw in another github post that you maybe working on estimation of aneuploidy as a possible addition to this package.  +1 to that !
