### ISSUE TITLE
how to control number of sub-clones ?

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [colomemaria/epiAneufinder#34]
Hello, is there a way to control the number of sub-clones

So far i did this - I wanted to get 2 sub-clones so i set tree_depth=2, but the sub-clone output still gives me clones from 1 - 4 and NA value. 

Is there way to control the number of sub-clones output ? Eg: I want 2 sub-clones

```
subclones <- epiAneufinder::split_subclones(res_table,
                                              tree_depth=2,
                                              plot_tree=TRUE,
                                              plot_path=paste0(sampleCNVpath,"/subclones.pdf"),
                                              plot_width=4,
                                              plot_height=3)

```

**Comment by thek71** [comment]
Hi Krithika,

I think that if you specify the tree depth at 1, then you will get the first two classes.
Please try using tree_depth =1 and just tell us if it worked.

Best,
Katia

**Comment by Krithika-Bhuvan** [comment]
Hello, the tree_depth=2 itself worked okay.
