### ISSUE TITLE
results_table.tsv rows are not the same size in multiple samples

### ISSUE THREAD

**Issue by tinakeshav** [colomemaria/epiAneufinder#4]
Hi epiAneufinder devs, 
Thank you for releasing such an easy-to-use package. 
I've used this package for multiple samples and the `results_table.tsv` data frame does not have the same number of rows for every sample. 
Initially I thought it's not saving rows that are all state 1 (normal), but there are rows in some samples that are only state 1. 
Could you kindly elaborate on why the row number of `results_table.tsv` differ from each other? 
Thank you so much!

**Comment by akshaya4r** [comment]
Hi tinakeshav,
For each sample, bins that have 0 counts in 85% or more of the population are removed such that the CNV calls aren't affected by other biases. This is why you could have different number of rows in the results table.
