### ISSUE TITLE
using epiAneufinder in CUT&Tag

### ISSUE THREAD

**Issue by nouroddinc** [colomemaria/epiAneufinder#6]
Thank you so much for preparing this useful package. I have used it on my ATAC-seq data and it clearly showed differences between malignant/normal cells. I was wondering is it possible to use epiAneufinder on CUT&Tag sequencing data?
Many Thanks,
Noori

**Comment by thek71** [comment]
Dear Noorti,

sorry for the late response. So far we have only tested epiAneufinder on methylation data. It would be interesting to try out on CUT&Tag, but this is not in our immediate plans.
We will add it in our list of possible extensions.

Best regards,
Katia
